# Site settings
title: Retorquere on GitHub
description: > # this means to ignore newlines until "baseurl:"
  Just random thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://retorquere.github.io" # the base hostname & protocol for your site
twitter_username: retorquere
github_username:  retorquere

# Build settings
markdown: kramdown
